### ISSUE TITLE
Zgłoszenie podszywającego się profilu

### ISSUE THREAD

**Issue by RimmarPL** [Wruczek/FakeCommentsHider#16]
Chcę zgłosić podszywający się profil "izak LIVE"

Informacje:
ID profilu: 100756836186987169573
Pozostawiony komentarz: +Alanos Rozdaje skiny! kilka nozy do zdobycia! Kto pierwszy? http://izakoskiny.lnfo.pl/
URL strony: https://www.youtube.com/watch?v=__2u_oxAlpI&feature=em-uploademail
URL komentarza: https://www.youtube.com/watch?v=__2u_oxAlpI&feature=em-uploademail&lc=z13mw3tx2p3tsbcko23mw1iyttz0v5tvl.1436114852574953

**Comment by Wruczek** [comment]
Dziękuję za zgłoszenie.

Podjęte działania (commit 3973349c25ddd90d6a8ff12bfff0ab3a2585d0ba):
-  zbanowano kilka profilów podszywających się pod izaka:
  - 111638198485564969187
  - 101404219544963812213
  - 101280134042997634185
  - 115196896377716799077
  - 108162774985861463628
  - 107189932925128301853
  - 106182250272191718982
- zbanowano wyrazy
  - https://steamcommunity.com/tradeoffer/new/?partner=201009373&token=vF8bD6xD
  - http://izakoskiny.lnfo.pl/

Zmiany mogą nie być widoczne od razu. Pozdrawiam!
