### ISSUE TITLE
Zgłoszenie podszywającego się profilu

### ISSUE THREAD

**Issue by RimmarPL** [Wruczek/FakeCommentsHider#5]
Chcę zgłosić podszywający się profil.

Informacje:
ID profilu: 100723143751903639197
Pozostawiony komentarz:  Gimper Hajsy, łapcie link do sklepu, gdzie macie bardzo tanie skiny cs:go. richzone.nd.pl
URL strony: https://www.youtube.com/watch?v=BlekxKS9v3w

**Comment by Wruczek** [comment]
Dziękuję za zgłoszenie.

Podjęte działania (commit 6ae95031a5283b471ea2454b0f497af359ded84b):
- dodano ID "100723143751903639197" do listy zbanowanych kont

Zmiany mogą nie być widoczne od razu. Pozdrawiam!
