### ISSUE TITLE
Zgłoszenie podszywającego się profilu

### ISSUE THREAD

**Issue by i-am-modie** [Wruczek/FakeCommentsHider#51]
Chcę zgłosić podszywający się profil "JJay Joker"

Informacje:
ID profilu: 103499671998603655759
Pozostawiony komentarz: +Brutal ! Zapraszam was do mojego giveawaya! Do zgarnięcia DARMOWE GRY STEAM!!!!! - http://jjayjoker.none.pl/
URL strony: https://www.youtube.com/watch?v=H-x2tfru9J0
URL komentarza: https://www.youtube.com/watch?v=H-x2tfru9J0&lc=z13mvtgyiq3ax3p1t22syd0z2pfziffaj04.1436638183514248

**Comment by Wruczek** [comment]
Dziękuję za zgłoszenie.

Podjęte działania (commit 23d0fe1d49d1d0941f369360c9ab1a75a517932c):
- dodano "jjayjoker.none.pl" do listy zbanowanych wyrazów

Zmiany mogą nie być widoczne od razu. Pozdrawiam!
