### ISSUE TITLE
Zgłoszenie podszywającego się profilu

### ISSUE THREAD

**Issue by ImJustToNy** [Wruczek/FakeCommentsHider#71]
Chcę zgłosić podszywający się profil "ízak LIVE"

Informacje:
ID profilu: 112944357198201312316
Pozostawiony komentarz: +izak LIVE Łapcie prezent!!!! 18tyś kodów!

 paysefcarddarmowy.ulinks.net
URL strony: https://www.youtube.com/watch?v=fJH0BqIDsYg
URL komentarza: https://www.youtube.com/watch?v=fJH0BqIDsYg&lc=z13iefjw1qqgcvsna22pd5uw5sishd5mt.1436719936179296

**Comment by Wruczek** [comment]
Czy posiadasz najnowszą wersję wtyczki (0.3)?

**Comment by Wruczek** [comment]
Ok, widzę. Profil został zbanowany.
